// swift-tools-version: 6.0
//
// SampleHost — minimal substrate-using reference iOS host。
//
// Background:before 2026-05-20 SampleHost was a scheme INSIDE
// `Before.xcodeproj` (the legacy host app)。 The Before severance
// (chapter post-MATURATION-ARC, commit f2d980ca) moved Before to
// `Archive/Legacy/Before.xcodeproj/`,leaving SampleHost without
// a build path。 This `Package.swift` (added 2026-05-21 in the
// SampleHost reconstitution chip) declares SampleHost as a
// standalone SPM package that depends on BehavioralAISubstrate
// via a sibling-path dependency。
//
// Platform target:**iOS 27** (macOS floor aligned to v14 for
// resolution only)。 SampleHost contains UIKit-using bench panels +
// SwiftUI iOS app shells (5 UIKit-using files,11 SwiftUI-only
// files,38 cross-platform helpers)。
//
// deep-audit P2-22 (2026-07-13): a bare `swift build` from macOS
// does NOT fail first on UIKit — it fails EARLIER, during dependency
// resolution, because BehavioralAISubstrate declares `.macOS(.v14)`
// while this package's implicit macOS floor was the SPM default
// (macOS 12): "the product depends on macOS 14, but the target
// requires macOS 12". We now declare `.macOS(.v14)` so the manifest
// resolves and the (correct, expected) UIKit compile error is what a
// macOS builder actually sees. Either way the sanctioned path is
// xcodebuild + an iOS simulator — `swift build` on macOS is not a
// supported build of an iOS-only host:
//
//   (run from INSIDE SampleHost/ — `-package-path` stopped resolving
//    under Xcode 27 beta, operator-verified 2026-07-11)
//   cd SampleHost && xcodebuild build \
//     -scheme SampleHost \
//     -destination 'platform=iOS Simulator,name=iPhone 17e'
//
//   cd SampleHost && xcodebuild test \
//     -scheme SampleHost \
//     -destination 'platform=iOS Simulator,name=iPhone 17e'
//
// (the trailing `-Package` scheme is auto-generated by Xcode
// for SPM-only projects when there's no .xcodeproj alongside)
//
// Substrate dependency:`../BehavioralAISubstrate` (sibling path,
// no version pin since both repos co-evolve)。
//
// Resources:5 CoreML model packages + 1 safetensors LoRA file
// shipped via `.process(...)` (SPM bundles them into the app
// resource directory)。

import PackageDescription

let package = Package(
    name: "SampleHost",
    platforms: [
        .iOS("27.0"),
        // deep-audit P2-22 (2026-07-13): align the macOS floor with BAS (.macOS(.v14)) so a
        // macOS `swift build` fails on the real UIKit imports, not a confusing implicit-floor
        // (macOS 12 default) vs dependency-floor mismatch during resolution.
        .macOS(.v14)
    ],
    products: [
        .library(name: "SampleHost", targets: ["SampleHost"])
    ],
    dependencies: [
        // Sibling path dependency — both packages live in the
        // same monorepo,so we co-evolve without versioning。
        // External adopters would replace this with a git-pinned
        // dep + a versioned tag (e.g。 .package(url: "...",
        // .upToNextMinor(from: "0.56.0")))。
        .package(path: "../BehavioralAISubstrate")
    ],
    targets: [
        // SampleHost library — all 59 Swift files at the
        // SampleHost/ root,plus 5 CoreML .mlpackage resources +
        // 1 safetensors LoRA。 No subdirectory layout because
        // SampleHost has been flat-files since chapter ~150。
        .target(
            name: "SampleHost",
            dependencies: [
                .product(name: "BASHostKit",
                         package: "BehavioralAISubstrate"),
                // M-o MED-2 follow-through (2026-07-11): BASConsoleView/BASHostConsoleView moved
                // out of the core into the SwiftUI-only BASAdminUI target; this consumer was
                // never updated (cross-package audit drift, same class as the VaultError one).
                .product(name: "BASAdminUI",
                         package: "BehavioralAISubstrate"),
                .product(name: "BASOrgan",
                         package: "BehavioralAISubstrate"),
                .product(name: "BASRuntimeCore",
                         package: "BehavioralAISubstrate"),
                .product(name: "BASMLXAdapter",
                         package: "BehavioralAISubstrate"),
                // charter audit 2026-07-12 T4 (LLM-outside cut): BASHostKit no longer
                // re-exports the model-adapter module, and the MLModel-bound Chenglu
                // builder overload moved to the edge-wiring ring. This HOST links both
                // sides explicitly — that is a host's prerogative and obligation.
                .product(name: "BASAppleAdapters",
                         package: "BehavioralAISubstrate"),
                .product(name: "BASAppleEdgeWiring",
                         package: "BehavioralAISubstrate")
            ],
            path: ".",
            exclude: [
                "Package.swift",
                "Tests"
            ],
            resources: [
                // `.copy` (not `.process`) preserves the .mlpackage
                // directory structure。 `.process` would flatten each
                // .mlpackage,which collides because every .mlpackage
                // contains `Manifest.json` + `model.mlmodel` +
                // `weight.bin` with the same names。 `.copy` keeps
                // each as a self-contained directory in the bundle。
                .copy("ChengluLatencyHead_v0.mlpackage"),
                .copy("ChengluLengthHead_v0.mlpackage"),
                .copy("ChengluMultiHead_v0.mlpackage"),
                .copy("ChengluPermitPredict_v0.mlpackage"),
                .copy("ChengluPreflight_v0.mlpackage"),
                .process("qinao_curriculum_lora_m247.safetensors")
            ]
        ),
        // SampleHostTests — 7 XCTest files testing the bench
        // helpers,BASHostKit invocation,CoreML stress runners,
        // and AFM timeout wrapper。 Most tests `@testable import`
        // SampleHost + BASHostKit。 SampleHostLLMExtractionDemoTests
        // additionally `@testable import`s BASOrgan + BASRuntimeCore
        // for direct organ-side testing。
        .testTarget(
            name: "SampleHostTests",
            dependencies: ["SampleHost"],
            path: "Tests/SampleHostTests"
        )
    ]
)
