import Foundation
import BASMemory
import BASObservability
import BASOrchestration
import BASPolicy
import BASRuntimeCore
import BASWorldPrior

/// The earlier cluster-bundle convenience inits (M1474…M1483). Public API preserved
/// verbatim from the pre-box ladder; every body delegates FLAT (one hop) to the
/// all-fields init — the pre-box 6-deep delegation ladder re-materialized the field
/// set per rung under -Onone and was the cooperative-pool stack killer.
extension BASEBrainTurnResult {

    /// M1483 4-bundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        contextFrame: BASContextFrame,
        decomposeFrame: BASDecomposeFrame,
        memoryBundle: BASMemoryBundle,
        thoughtFrame: BASThoughtFrame,
        thoughtFold: BASThoughtFold,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: contextFrame,
            decomposeFrame: decomposeFrame,
            memoryBundle: memoryBundle,
            thoughtFrame: thoughtFrame,
            thoughtFold: thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1482 3-bundle (host + sovereign + evolution) — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        contextFrame: BASContextFrame,
        decomposeFrame: BASDecomposeFrame,
        memoryBundle: BASMemoryBundle,
        thoughtFrame: BASThoughtFrame,
        thoughtFold: BASThoughtFold,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        kunlunAxisAlignment: BASAxisAlignment? = nil,
        humanAnchorSignal: BASHumanAnchorSignal? = nil,
        abyssalPressure: BASAbyssalPressure? = nil,
        unknownReserve: BASUnknownReserve? = nil,
        kunlunHeavenGatePermit: BASHeavenGatePermit? = nil,
        kunlunRiverOriginTrace: BASRiverOriginTrace? = nil,
        yaochiSanctumEntry: BASYaochiSanctumEntry? = nil
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: contextFrame,
            decomposeFrame: decomposeFrame,
            memoryBundle: memoryBundle,
            thoughtFrame: thoughtFrame,
            thoughtFold: thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: kunlunAxisAlignment,
            humanAnchorSignal: humanAnchorSignal,
            abyssalPressure: abyssalPressure,
            unknownReserve: unknownReserve,
            kunlunHeavenGatePermit: kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: kunlunRiverOriginTrace,
            yaochiSanctumEntry: yaochiSanctumEntry
        )
    }

    /// M1482 3-bundle (evolution + sovereign + auditProjectionForward) — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostConstitution: BASHostConstitution? = nil,
        hostConstitutionVault: BASHostConstitutionVault? = nil,
        hostVersionTree: BASHostVersionTree? = nil,
        hostForgetRequest: BASForgetRequest? = nil,
        hostContext: BASHostProfile,
        contextFrame: BASContextFrame,
        decomposeFrame: BASDecomposeFrame,
        memoryBundle: BASMemoryBundle,
        thoughtFrame: BASThoughtFrame,
        thoughtFold: BASThoughtFold,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostConstitution,
            hostConstitutionVault: hostConstitutionVault,
            hostVersionTree: hostVersionTree,
            hostForgetRequest: hostForgetRequest,
            hostContext: hostContext,
            contextFrame: contextFrame,
            decomposeFrame: decomposeFrame,
            memoryBundle: memoryBundle,
            thoughtFrame: thoughtFrame,
            thoughtFold: thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1478 2-bundle (sovereign + evolution) — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostConstitution: BASHostConstitution? = nil,
        hostConstitutionVault: BASHostConstitutionVault? = nil,
        hostVersionTree: BASHostVersionTree? = nil,
        hostForgetRequest: BASForgetRequest? = nil,
        hostContext: BASHostProfile,
        contextFrame: BASContextFrame,
        decomposeFrame: BASDecomposeFrame,
        memoryBundle: BASMemoryBundle,
        thoughtFrame: BASThoughtFrame,
        thoughtFold: BASThoughtFold,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        kunlunAxisAlignment: BASAxisAlignment? = nil,
        humanAnchorSignal: BASHumanAnchorSignal? = nil,
        abyssalPressure: BASAbyssalPressure? = nil,
        unknownReserve: BASUnknownReserve? = nil,
        kunlunHeavenGatePermit: BASHeavenGatePermit? = nil,
        kunlunRiverOriginTrace: BASRiverOriginTrace? = nil,
        yaochiSanctumEntry: BASYaochiSanctumEntry? = nil
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostConstitution,
            hostConstitutionVault: hostConstitutionVault,
            hostVersionTree: hostVersionTree,
            hostForgetRequest: hostForgetRequest,
            hostContext: hostContext,
            contextFrame: contextFrame,
            decomposeFrame: decomposeFrame,
            memoryBundle: memoryBundle,
            thoughtFrame: thoughtFrame,
            thoughtFold: thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: kunlunAxisAlignment,
            humanAnchorSignal: humanAnchorSignal,
            abyssalPressure: abyssalPressure,
            unknownReserve: unknownReserve,
            kunlunHeavenGatePermit: kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: kunlunRiverOriginTrace,
            yaochiSanctumEntry: yaochiSanctumEntry
        )
    }

    /// M1474 evolutionBundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignVerdict: BASSovereignVerdict? = nil,
        sovereignCommitTokens: [BASSovereignCommitToken] = [],
        sovereignWarrants: [BASSovereignWarrant] = [],
        sovereignLock: BASSovereignLock? = nil,
        quarantineRecords: [BASQuarantineRecord] = [],
        sovereignAuditEntry: BASSovereignAuditEntry? = nil,
        sovereignActuationCommands: [BASSovereignActuationCommand] = [],
        sovereignExecutionReceipts: [BASSovereignExecutionReceipt] = [],
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostConstitution: BASHostConstitution? = nil,
        hostConstitutionVault: BASHostConstitutionVault? = nil,
        hostVersionTree: BASHostVersionTree? = nil,
        hostForgetRequest: BASForgetRequest? = nil,
        hostContext: BASHostProfile,
        contextFrame: BASContextFrame,
        decomposeFrame: BASDecomposeFrame,
        memoryBundle: BASMemoryBundle,
        thoughtFrame: BASThoughtFrame,
        thoughtFold: BASThoughtFold,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        kunlunAxisAlignment: BASAxisAlignment? = nil,
        humanAnchorSignal: BASHumanAnchorSignal? = nil,
        abyssalPressure: BASAbyssalPressure? = nil,
        unknownReserve: BASUnknownReserve? = nil,
        kunlunHeavenGatePermit: BASHeavenGatePermit? = nil,
        kunlunRiverOriginTrace: BASRiverOriginTrace? = nil,
        yaochiSanctumEntry: BASYaochiSanctumEntry? = nil
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignVerdict,
            sovereignCommitTokens: sovereignCommitTokens,
            sovereignWarrants: sovereignWarrants,
            sovereignLock: sovereignLock,
            quarantineRecords: quarantineRecords,
            sovereignAuditEntry: sovereignAuditEntry,
            sovereignActuationCommands: sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostConstitution,
            hostConstitutionVault: hostConstitutionVault,
            hostVersionTree: hostVersionTree,
            hostForgetRequest: hostForgetRequest,
            hostContext: hostContext,
            contextFrame: contextFrame,
            decomposeFrame: decomposeFrame,
            memoryBundle: memoryBundle,
            thoughtFrame: thoughtFrame,
            thoughtFold: thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: kunlunAxisAlignment,
            humanAnchorSignal: humanAnchorSignal,
            abyssalPressure: abyssalPressure,
            unknownReserve: unknownReserve,
            kunlunHeavenGatePermit: kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: kunlunRiverOriginTrace,
            yaochiSanctumEntry: yaochiSanctumEntry
        )
    }
}
