import Foundation
import BASMemory
import BASObservability
import BASOrchestration
import BASPolicy
import BASRuntimeCore
import BASWorldPrior

/// The typed cluster-bundle convenience inits (M1474…M1506). Public API preserved
/// verbatim from the pre-box ladder; every body delegates FLAT (one hop) to the
/// all-fields init — the pre-box 6-deep delegation ladder re-materialized the field
/// set per rung under -Onone and was the cooperative-pool stack killer.
extension BASEBrainTurnResult {

    /// M1506 9-bundle (the production runTurn path) — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceLifecycleBundle: BASEBrainTurnResultDeviceLifecycleBundle,
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        forensicMetadataBundle: BASEBrainTurnResultForensicMetadataBundle,
        hostBundle: BASEBrainTurnResultHostBundle,
        cognitiveFramesBundle: BASEBrainTurnResultCognitiveFramesBundle,
        riskChoiceBundle: BASEBrainTurnResultRiskChoiceBundle,
        miscBundle: BASEBrainTurnResultMiscBundle,
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceLifecycleBundle.deviceState,
            budgetFrame: deviceLifecycleBundle.budgetFrame,
            wakeIntent: deviceLifecycleBundle.wakeIntent,
            vitalState: deviceLifecycleBundle.vitalState,
            runLease: deviceLifecycleBundle.runLease,
            emergencyBrake: deviceLifecycleBundle.emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: forensicMetadataBundle.policyLineage,
            recoveryDisposition: forensicMetadataBundle.recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: cognitiveFramesBundle.contextFrame,
            decomposeFrame: cognitiveFramesBundle.decomposeFrame,
            memoryBundle: cognitiveFramesBundle.memoryBundle,
            thoughtFrame: cognitiveFramesBundle.thoughtFrame,
            thoughtFold: cognitiveFramesBundle.thoughtFold,
            triScores: riskChoiceBundle.triScores,
            mergedChoice: riskChoiceBundle.mergedChoice,
            riskCard: riskChoiceBundle.riskCard,
            actionPermit: riskChoiceBundle.actionPermit,
            riskDecisionPackage: miscBundle.riskDecisionPackage,
            hostGateValue: miscBundle.hostGateValue,
            renderedOutput: miscBundle.renderedOutput,
            updateTickets: miscBundle.updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: forensicMetadataBundle.runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1502 8-bundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceLifecycleBundle: BASEBrainTurnResultDeviceLifecycleBundle,
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        cognitiveFramesBundle: BASEBrainTurnResultCognitiveFramesBundle,
        riskChoiceBundle: BASEBrainTurnResultRiskChoiceBundle,
        miscBundle: BASEBrainTurnResultMiscBundle,
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceLifecycleBundle.deviceState,
            budgetFrame: deviceLifecycleBundle.budgetFrame,
            wakeIntent: deviceLifecycleBundle.wakeIntent,
            vitalState: deviceLifecycleBundle.vitalState,
            runLease: deviceLifecycleBundle.runLease,
            emergencyBrake: deviceLifecycleBundle.emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: cognitiveFramesBundle.contextFrame,
            decomposeFrame: cognitiveFramesBundle.decomposeFrame,
            memoryBundle: cognitiveFramesBundle.memoryBundle,
            thoughtFrame: cognitiveFramesBundle.thoughtFrame,
            thoughtFold: cognitiveFramesBundle.thoughtFold,
            triScores: riskChoiceBundle.triScores,
            mergedChoice: riskChoiceBundle.mergedChoice,
            riskCard: riskChoiceBundle.riskCard,
            actionPermit: riskChoiceBundle.actionPermit,
            riskDecisionPackage: miscBundle.riskDecisionPackage,
            hostGateValue: miscBundle.hostGateValue,
            renderedOutput: miscBundle.renderedOutput,
            updateTickets: miscBundle.updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1498 7-bundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        cognitiveFramesBundle: BASEBrainTurnResultCognitiveFramesBundle,
        riskChoiceBundle: BASEBrainTurnResultRiskChoiceBundle,
        miscBundle: BASEBrainTurnResultMiscBundle,
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: cognitiveFramesBundle.contextFrame,
            decomposeFrame: cognitiveFramesBundle.decomposeFrame,
            memoryBundle: cognitiveFramesBundle.memoryBundle,
            thoughtFrame: cognitiveFramesBundle.thoughtFrame,
            thoughtFold: cognitiveFramesBundle.thoughtFold,
            triScores: riskChoiceBundle.triScores,
            mergedChoice: riskChoiceBundle.mergedChoice,
            riskCard: riskChoiceBundle.riskCard,
            actionPermit: riskChoiceBundle.actionPermit,
            riskDecisionPackage: miscBundle.riskDecisionPackage,
            hostGateValue: miscBundle.hostGateValue,
            renderedOutput: miscBundle.renderedOutput,
            updateTickets: miscBundle.updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1494 6-bundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        cognitiveFramesBundle: BASEBrainTurnResultCognitiveFramesBundle,
        riskChoiceBundle: BASEBrainTurnResultRiskChoiceBundle,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: cognitiveFramesBundle.contextFrame,
            decomposeFrame: cognitiveFramesBundle.decomposeFrame,
            memoryBundle: cognitiveFramesBundle.memoryBundle,
            thoughtFrame: cognitiveFramesBundle.thoughtFrame,
            thoughtFold: cognitiveFramesBundle.thoughtFold,
            triScores: riskChoiceBundle.triScores,
            mergedChoice: riskChoiceBundle.mergedChoice,
            riskCard: riskChoiceBundle.riskCard,
            actionPermit: riskChoiceBundle.actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }

    /// M1490 5-bundle — public API preserved verbatim; the body now delegates
    /// DIRECTLY to the all-fields init (the pre-box delegation LADDER was the
    /// stack killer: every rung re-materialized the field set under -Onone).
    public init(
        deviceState: BASDeviceState,
        budgetFrame: BASBudgetFrame,
        wakeIntent: BASWakeIntent,
        vitalState: BASVitalState,
        runLease: BASRunLease? = nil,
        emergencyBrake: BASEmergencyBrake = BASEmergencyBrake(
            brakeLevel: .none,
            reasonCodes: []
        ),
        sovereignBundle: BASEBrainTurnResultSovereignBundle,
        policyLineage: BASRuntimePolicyLineage? = nil,
        recoveryDisposition: BASRecoveryDisposition? = nil,
        hostBundle: BASEBrainTurnResultHostBundle,
        cognitiveFramesBundle: BASEBrainTurnResultCognitiveFramesBundle,
        triScores: [BASTriSelfScore],
        mergedChoice: BASMergedChoice,
        riskCard: BASRiskCard,
        actionPermit: BASActionPermit,
        riskDecisionPackage: BASRiskDecisionPackage? = nil,
        hostGateValue: Double,
        renderedOutput: BASRenderedOutput,
        updateTickets: [BASUpdateTicket],
        evolutionBundle: BASEBrainTurnResultEvolutionBundle,
        runtimeTrace: BASRuntimeTrace,
        auditProjectionForwardBundle: BASEBrainTurnResultAuditProjectionForwardBundle
    ) {
        self.init(
            deviceState: deviceState,
            budgetFrame: budgetFrame,
            wakeIntent: wakeIntent,
            vitalState: vitalState,
            runLease: runLease,
            emergencyBrake: emergencyBrake,
            sovereignVerdict: sovereignBundle.sovereignVerdict,
            sovereignCommitTokens: sovereignBundle.sovereignCommitTokens,
            sovereignWarrants: sovereignBundle.sovereignWarrants,
            sovereignLock: sovereignBundle.sovereignLock,
            quarantineRecords: sovereignBundle.quarantineRecords,
            sovereignAuditEntry: sovereignBundle.sovereignAuditEntry,
            sovereignActuationCommands: sovereignBundle.sovereignActuationCommands,
            sovereignExecutionReceipts: sovereignBundle.sovereignExecutionReceipts,
            policyLineage: policyLineage,
            recoveryDisposition: recoveryDisposition,
            hostConstitution: hostBundle.hostConstitution,
            hostConstitutionVault: hostBundle.hostConstitutionVault,
            hostVersionTree: hostBundle.hostVersionTree,
            hostForgetRequest: hostBundle.hostForgetRequest,
            hostContext: hostBundle.hostContext,
            contextFrame: cognitiveFramesBundle.contextFrame,
            decomposeFrame: cognitiveFramesBundle.decomposeFrame,
            memoryBundle: cognitiveFramesBundle.memoryBundle,
            thoughtFrame: cognitiveFramesBundle.thoughtFrame,
            thoughtFold: cognitiveFramesBundle.thoughtFold,
            triScores: triScores,
            mergedChoice: mergedChoice,
            riskCard: riskCard,
            actionPermit: actionPermit,
            riskDecisionPackage: riskDecisionPackage,
            hostGateValue: hostGateValue,
            renderedOutput: renderedOutput,
            updateTickets: updateTickets,
            experienceCandidates: evolutionBundle.experienceCandidates,
            workflowCandidates: evolutionBundle.workflowCandidates,
            guardTemplateCandidates: evolutionBundle.guardTemplateCandidates,
            biasRecords: evolutionBundle.biasRecords,
            riskPatternCandidates: evolutionBundle.riskPatternCandidates,
            learningExportBundles: evolutionBundle.learningExportBundles,
            shadowTrialRecords: evolutionBundle.shadowTrialRecords,
            versionDeltas: evolutionBundle.versionDeltas,
            retractionOrders: evolutionBundle.retractionOrders,
            evolutionSeals: evolutionBundle.evolutionSeals,
            runtimeTrace: runtimeTrace,
            kunlunAxisAlignment: auditProjectionForwardBundle.kunlunAxisAlignment,
            humanAnchorSignal: auditProjectionForwardBundle.humanAnchorSignal,
            abyssalPressure: auditProjectionForwardBundle.abyssalPressure,
            unknownReserve: auditProjectionForwardBundle.unknownReserve,
            kunlunHeavenGatePermit: auditProjectionForwardBundle.kunlunHeavenGatePermit,
            kunlunRiverOriginTrace: auditProjectionForwardBundle.kunlunRiverOriginTrace,
            yaochiSanctumEntry: auditProjectionForwardBundle.yaochiSanctumEntry
        )
    }
}
