// MARK: - BASEventLog — chapter 三百五四 / M841
//
// Phase P1 Foundation 第一刀: typed event-sourced log。Closes
// G1 from the chapter 三百五三 / M840 Chenglu Cognitive OS roadmap。
//
// ## Why this exists
//
// Per chapter 三百五三 / M840 audit, the existing memory pipeline is
// **atom-snapshot based**:`BASSQLiteMemoryAtomStore` (chapter
// 二百四十八 / M735) persists `BASGovernedMemory` rows and mutates
// them via `updateTier` / `updateGovernanceStatus` / `remove`。
// There is **no append-only event log** — turns happen, audit data
// flows through `BASEventRecord` in transit, but nothing persists
// the immutable temporal stream of what happened。
//
// G1 closes that gap。An event log is the foundational primitive
// for:
//   - G2 (chapter 三百五五):state vector S_t reducer needs an
//     ordered event stream as input
//   - G8 (chapter 三百X — P2):Mamba/SSM training data is exactly
//     this event stream + supervised labels
//   - G9 (chapter 三百X — P2):causal graph extraction walks
//     `(event_t-1, event_t, outcome)` triples from this log
//
// ## What this file ships (M841)
//
//   - `BASEventLogEntry` — Codable Sendable typed event row
//   - `BASEventLogStorage` — async protocol (atom-store mirror)
//   - `BASInMemoryEventLogStorage` — default opt-in conformer
//
// SQLite-backed conformer + replay runner ship in companion files:
// `BASEventLogSQLiteStorage.swift` + `BASEventReplayRunner.swift`。
//
// ## Doctrine pins held
//
//   - 不变量 #1 / #2 / #3 全保 — event log is observation plumbing,
//     no permit/verdict mutation
//   - 红线 7 watcher hint only — log writes are append-only audit
//     records,never feed runtime decisions
//   - 单提交口 (L11/L14) 不变 — log is consulted by SSM/causal
//     graph layers but those are hint-class (chapter 三百二三 doctrine)
//   - chapter 二百一一 single-source-of-truth: ONE event log entry
//     type;ONE protocol;the SQLite conformer mirrors the in-memory
//     conformer's contract bit-for-bit
//   - chapter 一百八十五 anti-magic-number: event kinds + source
//     types are typed enums,not free-form strings
//   - ADR-014 OPT-IN → PROD: storage parameter defaults to nil on
//     `BASHostRuntime`,zero behavior change for existing call sites
//   - chapter 二百四十八 M735 storage idiom: actor isolation +
//     typed StorageError + WAL mode + transient-destructor binding
//     mirrored exactly in the SQLite conformer
//
// ## Schema invariants
//
//   - `eventID` is unique (UUIDv4 generated by writer)
//   - `timestampMs` is wall-clock at write time (monotonic ordering
//     within a session is NOT guaranteed — use `sequenceNumber` for
//     intra-session order)
//   - Events are **immutable** post-write (no update path; only
//     append + read + replay)
//   - `payloadJson` may be nil for minimal events;when present it
//     is a free-form Sendable Codable extension surface for forward-
//     compat
//
// ## Non-goals
//
//   - In-loop write-back to user-visible state (events flow
//     forward only — replay is a separate process)
//   - GDPR / forget-cascade integration (chapter 一百二 五级删除
//     doctrine handles that at the L11 sovereign vault layer; event
//     log can also be erased but that's a host-driven workflow,
//     not part of this chapter)
//   - Cross-device sync (chapter 三百一九 BASMeshSyncFrame schema
//     covers that for mesh state;event log sync is a future chapter)

import Foundation

// MARK: - Event kind (typed)

/// Canonical event kind taxonomy。Mirrors user vision §8 event-stream
/// catalog — chat / voice / image / file / web / calendar / health /
/// app-behavior — plus internal lifecycle events。
public enum BASEventLogKind: String, Codable, Equatable, Sendable,
    CaseIterable
{
    /// User typed text (chat / message)
    case chat = "chat"
    /// User spoke (voice transcription)
    case voice = "voice"
    /// User shared an image
    case image = "image"
    /// User shared a file
    case file = "file"
    /// User shared a URL or web page
    case web = "web"
    /// Calendar / schedule signal
    case calendar = "calendar"
    /// Health (HealthKit) signal
    case health = "health"
    /// Generic app-behavior event (focus / open / dismiss)
    case appBehavior = "app-behavior"
    /// Session lifecycle (start / resume / end)
    case sessionLifecycle = "session-lifecycle"
    /// Tool/agent invocation (chapter 三百X — P1 G6)
    case toolInvocation = "tool-invocation"
    /// Substrate audit (per-turn audit emission)
    case substrateAudit = "substrate-audit"
    /// Internal (eg. checkpoint / migration)
    case internalSignal = "internal-signal"
}

// MARK: - Risk band (typed)

/// Coarse risk tag captured in event row。Detailed risk shape lives
/// in `BASRiskCard`; this is a 1-byte summary for fast filter.
public enum BASEventLogRiskBand: String, Codable, Equatable,
    Sendable, CaseIterable
{
    case low
    case medium
    case high
    case unknown
}

// MARK: - Event log entry

/// Typed append-only event log row。Mirrors the user vision §8
/// event-stream schema with explicit Codable surface for SQLite
/// payload_json column。
///
/// All fields except `eventID` / `timestampMs` / `kind` /
/// `sessionID` / `sequenceNumber` are optional — minimal events
/// carry just the required identity quintet。Detail enrichment is
/// caller-driven (BASEventLogEntryBuilder factories live in
/// BASEventLogBuilder.swift, future M842 / G2 adds the
/// state_before/after IDs)。
public struct BASEventLogEntry: Codable, Equatable, Sendable {

    // MARK: - Required identity

    /// Stable UUIDv4 — primary key in storage layer。Caller
    /// generates;storage validates uniqueness。
    public let eventID: String

    /// Wall-clock timestamp at write site (millis since UNIX
    /// epoch)。NOT monotonic across processes — use
    /// `sequenceNumber` for intra-session order。
    public let timestampMs: Int64

    /// Typed event kind per `BASEventLogKind` taxonomy。
    public let kind: BASEventLogKind

    /// Session ID this event belongs to。Used to filter on
    /// replay。Empty string permitted for cross-session
    /// system events。
    public let sessionID: String

    /// Strictly-increasing-within-session sequence number。
    /// Storage layer assigns this on write (caller passes 0)。
    /// Replay relies on this for stable ordering。
    public let sequenceNumber: Int64

    // MARK: - Source / origin (optional)

    /// Logical source of this event (eg. "host.chat",
    /// "samplehost.bench-loop", "widget.timer")。
    public let source: String?

    /// Free-form turn reference if applicable。Empty for events
    /// that don't bind to a single turn。
    public let turnRef: String?

    // MARK: - Content classification (optional)

    /// Hash / digest of raw input — never the raw text itself
    /// (privacy doctrine)。Caller computes (eg. SHA256 prefix +
    /// length)。
    public let rawInputDigest: String?

    /// Intent classifier output (eg. "ask_question",
    /// "command", "share_observation")。
    public let intent: String?

    /// Emotion tag (eg. "calm", "anxious")。Mirrors
    /// `BASChengluFeatureEncoder.tones`。
    public let emotion: String?

    /// Risk band (low/medium/high/unknown)。
    public let riskBand: BASEventLogRiskBand

    /// Project name if event tags a project context。
    public let project: String?

    // MARK: - Cross-references (optional)

    /// Memory atom IDs that were retrieved / produced as part
    /// of this event's processing。
    public let memoryRefs: [String]

    /// State vector ID at event start (S_{t-1})。Filled by G2 /
    /// M842 — `BASUserStateStore` returns the ID of the
    /// most-recent S_t snapshot before reducer fires。
    public let stateBeforeID: String?

    /// State vector ID after event reducer ran (S_t)。Filled by
    /// G2 / M842。Pre-G2 events leave this nil。
    public let stateAfterID: String?

    /// Action codes emitted during event processing (eg.
    /// "permit:answer", "tool:searchMemory", "skip:thermal-pause")。
    public let actions: [String]

    /// Confidence score 0..1 (caller-determined semantic;
    /// typically classifier confidence on the dominant tag)。
    public let confidence: Double

    // MARK: - Forward-compat extension surface

    /// Free-form JSON-encoded extension payload。Caller stamps
    /// any additional Sendable Codable struct here;readers that
    /// don't recognize the schema ignore safely。
    public let payloadJson: String?

    // MARK: - Init

    public init(
        eventID: String,
        timestampMs: Int64,
        kind: BASEventLogKind,
        sessionID: String,
        sequenceNumber: Int64,
        source: String? = nil,
        turnRef: String? = nil,
        rawInputDigest: String? = nil,
        intent: String? = nil,
        emotion: String? = nil,
        riskBand: BASEventLogRiskBand = .unknown,
        project: String? = nil,
        memoryRefs: [String] = [],
        stateBeforeID: String? = nil,
        stateAfterID: String? = nil,
        actions: [String] = [],
        confidence: Double = 0,
        payloadJson: String? = nil
    ) {
        self.eventID = eventID
        self.timestampMs = timestampMs
        self.kind = kind
        self.sessionID = sessionID
        self.sequenceNumber = sequenceNumber
        self.source = source
        self.turnRef = turnRef
        self.rawInputDigest = rawInputDigest
        self.intent = intent
        self.emotion = emotion
        self.riskBand = riskBand
        self.project = project
        self.memoryRefs = memoryRefs
        self.stateBeforeID = stateBeforeID
        self.stateAfterID = stateAfterID
        self.actions = actions
        // Clamp confidence to [0, 1] — invariant for downstream
        // training pipelines (chapter 一百八十五 anti-magic-number
        // — clamp at the value boundary,not at every consumer)。
        self.confidence = max(0, min(1, confidence))
        self.payloadJson = payloadJson
    }
}

// MARK: - Event log head value projection

/// Immutable projection of one session's integrity-bound EventLog
/// position. This value carries evidence but grants no append, CAS,
/// sequencing, or integrity authority; only the selected EventLog
/// storage owner can establish or validate a current head.
public struct BASEventLogHead: Codable, Sendable, Equatable, Hashable {
    public let sessionID: String
    public let sequenceNumber: Int64
    public let eventID: String
    public let integrityDigest: String

    public init(
        sessionID: String,
        sequenceNumber: Int64,
        eventID: String,
        integrityDigest: String
    ) {
        self.sessionID = sessionID
        self.sequenceNumber = sequenceNumber
        self.eventID = eventID
        self.integrityDigest = integrityDigest
    }

    /// Structural no-event head sentinel. Its all-zero digest is a
    /// head/CAS sentinel, not the first integrity row's `prevHash`.
    public static func genesis(sessionID: String) -> Self {
        Self(
            sessionID: sessionID,
            sequenceNumber: -1,
            eventID: "",
            integrityDigest: String(repeating: "0", count: 64)
        )
    }
}

// MARK: - Storage protocol

/// Append-only typed event log storage。
///
/// **Contract**:
///   - `append(_:)` is **idempotent on duplicate eventID** —
///     re-appending the same eventID returns `false` (was-new
///     flag) and does NOT mutate the stored row。This protects
///     against double-write on retry。
///   - `append(_:)` returns the storage-assigned sequenceNumber
///     (storage owns sequence increment)。Callers should NOT
///     pre-assign sequenceNumber on their entry — the storage
///     layer overwrites it。
///   - `events(forSession:)` returns events ordered by
///     `sequenceNumber` ascending — replay invariant。
///   - `events(since:limit:)` returns events with timestampMs >=
///     `since`,bounded by `limit`。Used by G8 SSM training data
///     extraction。
///   - `count` reflects total rows including replays;hosts use
///     it for diagnostic emission。
///
/// **Sendable**: protocol conformers must be Sendable;all methods
/// are async because conformers may use actor isolation。
public protocol BASEventLogStorage: Sendable {

    /// Append a new event。Returns `(wasNew, assignedSequenceNumber)`。
    /// `wasNew` is `false` if the eventID already existed (idempotent
    /// retry semantics)。
    @discardableResult
    func append(
        _ entry: BASEventLogEntry
    ) async throws -> (
        wasNew: Bool, assignedSequenceNumber: Int64)

    /// Read events for a single session,ordered by sequenceNumber
    /// ascending。Returns empty array if session has no events。
    func events(
        forSession sessionID: String
    ) async -> [BASEventLogEntry]

    /// Read events with `timestampMs >= since`,limit applied
    /// after ordering by `(timestampMs ASC, sequenceNumber ASC)`。
    /// Used by training-data extraction (G8) and replay (G9)。
    func events(
        sinceTimestampMs since: Int64,
        limit: Int
    ) async -> [BASEventLogEntry]

    /// Total event count (all sessions)。
    var totalCount: Int { get async }

    /// Chapter 三百九七 / M896 retention policy:delete events
    /// with `timestampMs < cutoff`。Returns count of rows
    /// removed。Hosts call this periodically (e.g. once per
    /// hour) to bound disk / memory growth on long-running
    /// sessions。
    ///
    /// **Doctrine pin** (chapter 一百二 五级删除):this is real
    /// DELETE,not tombstone。Per the existing event-log
    /// append-only contract,events should not be deleted
    /// during a host session — but for storage retention on
    /// iPhone (where 8h × 600 iter/s = 11 GB without retention)
    /// it's necessary。Hosts opt in;default behavior is
    /// retain-everything。
    ///
    /// Idempotent on already-pruned cutoff (returns 0)。Older
    /// events filtered out atomically (storage actor isolation
    /// guarantees no concurrent reads see partial state)。
    @discardableResult
    func pruneEventsBefore(
        timestampMs cutoff: Int64
    ) async throws -> Int
}

// MARK: - Retention policy

/// Typed retention policy hosts attach to a periodic prune
/// scheduler。Chapter 三百九七 / M896 — closes the audit-flagged
/// "no retention strategy" gap for long-running iPhone sessions。
public struct BASEventLogRetentionPolicy:
    Sendable, Equatable, Hashable
{
    /// Maximum age in seconds。Events older than `now - maxAgeSec`
    /// are eligible for prune。0 = no age limit。
    public let maxAgeSec: Int64

    /// Optional override of the prune cadence。Hosts that want
    /// to drive prune themselves can ignore this and call
    /// `pruneEventsBefore(...)` on their own schedule。Default
    /// 3600 sec (1 hour)。
    public let pruneCadenceSec: Int64

    public init(
        maxAgeSec: Int64,
        pruneCadenceSec: Int64 = 3_600
    ) {
        self.maxAgeSec = max(0, maxAgeSec)
        self.pruneCadenceSec = max(60, pruneCadenceSec)
    }

    /// Common semantic-window preset: request pruning of event timestamps older
    /// than 24 hours. Shipped concrete stores additionally require the row to
    /// have spent more than 72 hours in storage before physically deleting it.
    public static let last24Hours =
        BASEventLogRetentionPolicy(
            maxAgeSec: 24 * 3600,
            pruneCadenceSec: 3600)

    /// Common semantic-window preset matching the independent physical
    /// ingestion floor enforced by the shipped concrete stores.
    public static let last72Hours =
        BASEventLogRetentionPolicy(
            maxAgeSec: 72 * 3600,
            pruneCadenceSec: 3600)

    /// Common preset:keep last 7 days,prune every 6 hours。
    public static let lastWeek =
        BASEventLogRetentionPolicy(
            maxAgeSec: 7 * 24 * 3600,
            pruneCadenceSec: 6 * 3600)

    /// Compute the cutoff timestamp for a host calling
    /// `pruneEventsBefore(...)` at `nowMs`。Returns the
    /// timestamp boundary;events with `timestampMs < cutoff`
    /// should be pruned。
    public func cutoff(nowMs: Int64) -> Int64 {
        guard maxAgeSec > 0 else { return 0 }
        let (ageMs, multiplyOverflow) = maxAgeSec.multipliedReportingOverflow(by: 1_000)
        guard !multiplyOverflow else { return 0 }
        let (cutoff, subtractOverflow) = nowMs.subtractingReportingOverflow(ageMs)
        guard !subtractOverflow, cutoff > 0 else { return 0 }
        return cutoff
    }
}

// MARK: - In-memory conformer (default / test)

/// Default in-memory `BASEventLogStorage` conformer。Hosts that
/// don't wire SQLite-backed storage but want event logging in-process
/// (eg. tests,one-shot CLI runs) use this。
///
/// Storage is process-scoped;does NOT persist across restarts。
/// For cross-session continuity use `BASSQLiteEventLogStorage`。
public actor BASInMemoryEventLogStorage: BASEventLogStorage {

    private struct StoredEntry: Sendable {
        let entry: BASEventLogEntry
        let ingestedAtMs: Int64
    }

    private var entries: [StoredEntry] = []
    private var idIndex: Set<String> = []
    private var sessionSequenceCounters: [String: Int64] = [:]
    private let nowMs: @Sendable () -> Int64

    public init() {
        self.nowMs = BASEventLogRecoveryRetention.systemNowMs
    }

    init(nowMs: @escaping @Sendable () -> Int64) {
        self.nowMs = nowMs
    }

    @discardableResult
    public func append(
        _ entry: BASEventLogEntry
    ) async throws -> (
        wasNew: Bool, assignedSequenceNumber: Int64)
    {
        if idIndex.contains(entry.eventID) {
            // Idempotent: find existing entry's sequenceNumber
            let existing = entries.first {
                $0.entry.eventID == entry.eventID
            }
            return (
                wasNew: false,
                assignedSequenceNumber:
                    existing?.entry.sequenceNumber ?? 0)
        }
        let sessionSeq = (
            sessionSequenceCounters[entry.sessionID] ?? -1
        ) + 1
        sessionSequenceCounters[entry.sessionID] = sessionSeq
        let stamped = BASEventLogEntry(
            eventID: entry.eventID,
            timestampMs: entry.timestampMs,
            kind: entry.kind,
            sessionID: entry.sessionID,
            sequenceNumber: sessionSeq,
            source: entry.source,
            turnRef: entry.turnRef,
            rawInputDigest: entry.rawInputDigest,
            intent: entry.intent,
            emotion: entry.emotion,
            riskBand: entry.riskBand,
            project: entry.project,
            memoryRefs: entry.memoryRefs,
            stateBeforeID: entry.stateBeforeID,
            stateAfterID: entry.stateAfterID,
            actions: entry.actions,
            confidence: entry.confidence,
            payloadJson: entry.payloadJson)
        let maximumStamp = entries.map(\.ingestedAtMs).max()
        let ingestionStamp = BASEventLogRecoveryRetention.clampedStamp(
            nowMs: nowMs(), maximumValidStamp: maximumStamp)
        entries.append(StoredEntry(entry: stamped, ingestedAtMs: ingestionStamp))
        idIndex.insert(stamped.eventID)
        return (wasNew: true, assignedSequenceNumber: sessionSeq)
    }

    public func events(
        forSession sessionID: String
    ) async -> [BASEventLogEntry] {
        entries
            .map(\.entry)
            .filter { $0.sessionID == sessionID }
            .sorted { $0.sequenceNumber < $1.sequenceNumber }
    }

    public func events(
        sinceTimestampMs since: Int64,
        limit: Int
    ) async -> [BASEventLogEntry] {
        let safeLimit = max(0, limit)
        guard safeLimit > 0 else { return [] }
        return entries
            .map(\.entry)
            .filter { $0.timestampMs >= since }
            .sorted { lhs, rhs in
                if lhs.timestampMs != rhs.timestampMs {
                    return lhs.timestampMs < rhs.timestampMs
                }
                return lhs.sequenceNumber < rhs.sequenceNumber
            }
            .prefix(safeLimit)
            .map { $0 }
    }

    public var totalCount: Int {
        entries.count
    }

    @discardableResult
    public func pruneEventsBefore(
        timestampMs cutoff: Int64
    ) async throws -> Int {
        guard cutoff > 0,
              let ingestionCutoff = BASEventLogRecoveryRetention.ingestionCutoff(nowMs: nowMs())
        else { return 0 }
        let beforeCount = entries.count
        entries.removeAll {
            $0.entry.timestampMs < cutoff
                && $0.ingestedAtMs < ingestionCutoff
        }
        let removed = beforeCount - entries.count
        if removed > 0 {
            // Rebuild idIndex to match new entries set
            idIndex = Set(entries.map { $0.entry.eventID })
            // Note:sessionSequenceCounters intentionally NOT
            // reset。Sequence numbers continue monotonically
            // from where they were,so future appends in the
            // same session don't collide with already-emitted
            // sequence numbers (preserved in audit downstream)。
        }
        return removed
    }
}
