import Foundation

/// audit devicetestapp MED-5 — the single source of truth for the Qwen3.5 FUSED-asset
/// GDN state-row width, extracted from the iOS-only DeviceTestApp so the constant is
/// pinned and macOS-unit-testable (the BASBurnInDeadline precedent).
///
/// The fused chain assets (Qwen35fused_asset1/2/3body/head) are generated by
/// `Tools/qwen35_3asset_fused.py` with a `state_all` row of
/// `ROW = GDN_S + GDN_C = 524288 + 24576 = 548864` (and `Tools/qwen35_headsplit.py`
/// imports the same ROW). The M4 arm hardcoded `548_864` correctly, but the M3
/// chain-fidelity probe reused the M1 TOY-probe width `stateRow` (default 524_288 =
/// GDN state only, dropping the 24_576-wide GDN conv band) — so by default M3
/// allocated a state buffer 24_576 columns short and the top-5-overlap fidelity check
/// ran on a mis-shaped state, defeating the very check the probe exists for.
///
/// M1's toy probe (`Qwen35Real_probe`, `[8, 524288]`) genuinely IS GDN-only, so its
/// 524_288 width is correct and untouched — this constant is ONLY the fused-chain row.
public enum BASQwen35FusedStateGeometry {
    /// GDN recurrent state width (GV·GHD·GHD). The M1 toy-probe row.
    public static let gdnState = 524_288
    /// GDN short-conv state band (3·8192) — present in the FUSED assets, absent from
    /// the toy probe. Omitting it is exactly the M3 bug.
    public static let gdnConv = 24_576
    /// The fused-asset `state_all` row width: GDN recurrent + conv band.
    /// Mirrors `ROW = GDN_S + GDN_C` in Tools/qwen35_3asset_fused.py.
    public static let row = gdnState + gdnConv   // 548_864
}
