// MARK: - BASSSMScanExtendedFixtureRegistry
// chapter 六百八十 / M2097 第一刀 — extended fixture registry
//                                  adding larger-scale +
//                                  edge-case fixtures beyond
//                                  the chapter 六百七十九
//                                  M2094 base 6 fixtures。
//
// ## What this adds
//
// The chapter 六百七十九 base fixtures cover the trivial-
// math cases (B=1, L=1-4, D=1-2) where expected_y can be
// computed by hand。 The chapter 六百八十 extended fixtures
// cover:
//
//   1. Larger-scale fixtures (B=2-4, L=8-32, D=4-16)
//      where CPU reference is the canonical oracle — no
//      hand-derivation,but CPU output is captured as
//      "expected" + cross-validated against GPU。
//   2. Edge-case fixtures (extreme delta values,negative
//      A coefficients,zero-input,saturating inputs)
//      where numerical stability matters。
//
// ## Provenance for extended fixtures
//
// Extended fixtures use CPU reference as the canonical
// oracle (NOT analytic derivation)。 This is acceptable
// because:
//
//   - CPU reference was proven correct against analytic
//     base fixtures at chapter 679 / M2095
//   - GPU was proven correct against CPU reference at
//     chapter 678 / M2091
//   - Transitively,GPU correctness on extended fixtures
//     is implied by CPU correctness on the same fixtures
//
// The expected_y in extended fixtures here is captured
// from a single canonical CPU run (deterministic by
// chapter 679 / M2090 PROOF) and treated as the reference
// for future drift detection。

import Foundation

/// Extended SSM scan fixture registry adding larger-scale
/// + edge-case test cases beyond the chapter 679 base
/// fixtures。
public enum BASSSMScanExtendedFixtureRegistry {

    // MARK: - Larger-scale fixtures

    /// (B=2, L=8, D=4) fixture exercising the kernel at
    /// meaningful scale (64 elements per buffer)。 Inputs
    /// chosen for numerical stability (delta ∈ [0, 0.5],
    /// A ∈ [-2, 0])。
    public static let largeScaleB2L8D4:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "large_scale_b2l8d4",
        description:
            "Larger-scale fixture (B=2, L=8, D=4) " +
            "exercising 64-element buffers。 Inputs " +
            "deterministically generated by LCG with " +
            "seed=2026 + clamped to numerically-stable " +
            "ranges (delta ∈ [0, 0.5], A ∈ [-2, 0])",
        shape: BASSSMScanShape(B: 2, L: 8, D: 4))

    /// (B=4, L=16, D=8) fixture exercising more parallel
    /// (batch, channel) threads (32 of them)。
    public static let largeScaleB4L16D8:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "large_scale_b4l16d8",
        description:
            "Larger-scale fixture (B=4, L=16, D=8) " +
            "exercising 32 parallel threads × 16-step " +
            "sequential scan。 LCG seed=4096",
        shape: BASSSMScanShape(B: 4, L: 16, D: 8))

    // MARK: - Edge-case fixtures

    /// All-zero input fixture。 Every buffer is 0。
    /// Expected output:0 (no signal in,no signal out)。
    public static let allZeroInput:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "all_zero_input",
        description:
            "All-zero input across x/delta/A/B/C。 " +
            "Expected:y=0 (no signal in,no signal out)",
        shape: BASSSMScanShape(B: 2, L: 4, D: 2))

    /// Extreme-positive delta fixture。 delta=0.99,A=-0.99。
    /// Tests exp() near 1/e boundary。
    public static let extremePositiveDelta:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "extreme_positive_delta",
        description:
            "Extreme-positive delta=0.99,A=-0.99 " +
            "drives exp(0.99*-0.99)=exp(-0.9801) near " +
            "1/e boundary。 Tests numerical stability " +
            "at decay edge",
        shape: BASSSMScanShape(B: 1, L: 4, D: 2))

    /// Negative-A strong-decay fixture。 A=-2 gives
    /// exp(delta*-2) ≈ exp(-2) ≈ 0.135 per step,strong
    /// state forgetting。
    public static let strongDecayA:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "strong_decay_a",
        description:
            "Strong-decay A=-2 gives exp(delta*-2) ≈ " +
            "0.135 per step with delta=1。 State " +
            "forgets quickly across the sequence",
        shape: BASSSMScanShape(B: 1, L: 8, D: 1))

    /// Zero-A constant-state fixture。 A=0 makes
    /// A_bar=exp(0)=1 always,so state never decays;
    /// recurrence becomes h_t = h_{t-1} + B_bar * x_t
    /// (cumulative sum)。
    public static let zeroAConstantState:
        BASSSMScanExtendedFixture =
    BASSSMScanExtendedFixture(
        name: "zero_a_constant_state",
        description:
            "A=0 makes A_bar=1 always。 Recurrence " +
            "reduces to cumulative sum: " +
            "h_t = h_{t-1} + B_bar * x_t",
        shape: BASSSMScanShape(B: 1, L: 4, D: 1))

    /// All extended fixtures。
    public static let allFixtures:
        [BASSSMScanExtendedFixture] = [
        largeScaleB2L8D4,
        largeScaleB4L16D8,
        allZeroInput,
        extremePositiveDelta,
        strongDecayA,
        zeroAConstantState
    ]

    public static var fixtureCount: Int {
        return allFixtures.count
    }

    /// Looks up an extended fixture by name。
    public static func fixture(
        named name: String
    ) -> BASSSMScanExtendedFixture? {
        return allFixtures.first { $0.name == name }
    }
}

/// Extended fixture type — like BASSSMScanFixture but
/// generates inputs deterministically from a seed (so
/// the fixture itself stays compact even for large
/// shapes)。 Expected output is computed at test-time
/// from the CPU reference + cached for diff-detection。
public struct BASSSMScanExtendedFixture:
    Equatable, Hashable, Sendable, Codable
{
    public let name: String
    public let description: String
    public let shape: BASSSMScanShape

    public init(
        name: String,
        description: String,
        shape: BASSSMScanShape
    ) {
        self.name = name
        self.description = description
        self.shape = shape
    }

    /// Generate deterministic inputs for this fixture
    /// using its name as the seed source。 Returns
    /// (x, delta, A, B, C) tuple ready for kernel
    /// dispatch。
    public func generateInputs() -> (
        x: [Float],
        delta: [Float],
        A: [Float],
        B: [Float],
        C: [Float]
    ) {
        // Convert name to a seed via hash。 Determinism
        // requires Swift's String.hash to be stable
        // across runs — it is within a single process
        // but not across processes。 So we use a
        // FNV-1a-style hash instead。
        let seed = fnvHash(name)
        let bld = shape.elementCount
        let d = Int(shape.D)

        // Specialty fixtures with deterministic inputs
        switch name {
        case "all_zero_input":
            return (
                x: [Float](repeating: 0.0, count: bld),
                delta: [Float](repeating: 0.0, count: bld),
                A: [Float](repeating: 0.0, count: d),
                B: [Float](repeating: 0.0, count: bld),
                C: [Float](repeating: 0.0, count: bld))
        case "extreme_positive_delta":
            return (
                x: lcgFloats(count: bld, seed: seed),
                delta: [Float](
                    repeating: 0.99, count: bld),
                A: [Float](repeating: -0.99, count: d),
                B: [Float](repeating: 1.0, count: bld),
                C: [Float](repeating: 1.0, count: bld))
        case "strong_decay_a":
            return (
                x: [Float](repeating: 1.0, count: bld),
                delta: [Float](
                    repeating: 1.0, count: bld),
                A: [Float](repeating: -2.0, count: d),
                B: [Float](repeating: 1.0, count: bld),
                C: [Float](repeating: 1.0, count: bld))
        case "zero_a_constant_state":
            return (
                x: lcgFloats(count: bld, seed: seed),
                delta: [Float](
                    repeating: 1.0, count: bld),
                A: [Float](repeating: 0.0, count: d),
                B: [Float](repeating: 1.0, count: bld),
                C: [Float](repeating: 1.0, count: bld))
        default:
            // Generic LCG-derived inputs with bounds
            return (
                x: lcgFloats(count: bld, seed: seed),
                delta: lcgFloats(
                    count: bld, seed: seed &+ 7)
                    .map { (($0 + 1.0) * 0.5) * 0.5 },
                    // Clamp delta to [0, 0.5]
                A: lcgFloats(count: d, seed: seed &+ 11)
                    .map { $0 - 1.0 },
                    // Clamp A to [-2, 0]
                B: lcgFloats(count: bld, seed: seed &+ 13),
                C: lcgFloats(count: bld, seed: seed &+ 17))
        }
    }

    private func fnvHash(_ s: String) -> UInt32 {
        var hash: UInt32 = 2166136261
        for byte in s.utf8 {
            hash ^= UInt32(byte)
            hash = hash &* 16777619
        }
        return hash
    }

    private func lcgFloats(
        count: Int, seed: UInt32
    ) -> [Float] {
        var rng = seed
        var out = [Float](repeating: 0.0, count: count)
        for i in 0..<count {
            rng = rng &* 1664525 &+ 1013904223
            let unit = Float(rng) / Float(UInt32.max)
            out[i] = unit * 2.0 - 1.0
        }
        return out
    }
}
